### ISSUE TITLE
Your lib is amazing

### ISSUE THREAD

**Issue by KnewHow** [tqk2811/TqkLibrary.Wpf.Interop.DirectX#1]
I use the `Microsoft.Wpf.Interop.DirectX-x64` in my project, when I run this project, it give me an error: `FileNotFoundException: 未能加载文件或程序集“Microsoft.Wpf.Interop.DirectX.dll”或它的某一个依赖项。找不到指定的模块`, but use this lib, I can run success. Can you tell me what you do? Thank you very much!

**Comment by tqk2811** [comment]
Thank.
____________________
Maybe you missing build target, AnyCpu will not work. 
And i don't  think, my lib work with AnyCpu.

**Comment by KnewHow** [comment]
I have modify the `AnyCpu` to x64, But your lib can be run success, but the `Microsoft.Wpf.Interop.DirectX-x64` run failure

**Comment by tqk2811** [comment]
I dont know why MS lib donot copy to output dir (maybe you use old visual studio ver or something). However, you just manual copy that dll to output dir.
Please continue your issues [here](https://github.com/microsoft/WPFDXInterop/issues/46)
